name: Moodle Plugin CI

# Test non-code skipping at the exact workflow revision.

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
  workflow_dispatch:
    inputs:
      moodle-core-branch:
        description: 'Moodle core branch to test against (if not provided, the branch will be auto-detected)'
        required: false
        type: string
  repository_dispatch:
    types: [moodle-plugin-ci]

jobs:
  moodle-plugin-ci:
    uses: scha-ms/moodle-workflows/.github/workflows/moodle-plugin-ci.yml@a62ea3bc288a1c1f4136d63d816dc5bf8b3d28f6
    with:
      moodle-core-branch: ${{ inputs.moodle-core-branch || github.event.client_payload.moodle-core-branch }}
      pr-check-body-contains: CI-SKIP-TEST
    secrets:
      GENERIC_USERNAME_1: ${{ secrets.GENERIC_USERNAME_1 }}
      GENERIC_PASSWORD_1: ${{ secrets.GENERIC_PASSWORD_1 }}
      GENERIC_USERNAME_2: ${{ secrets.GENERIC_USERNAME_2 }}
      GENERIC_PASSWORD_2: ${{ secrets.GENERIC_PASSWORD_2 }}
